network_dir = "network"
network_listen_address = "0.0.0.0"
# network_enr_address = ""
# network_enr_tcp_port = 1234
# network_enr_udp_port = 1234
network_libp2p_port = 1234
network_discovery_port = 1234
network_target_peers = 3
network_boot_nodes = ["/ip4/54.219.26.22/udp/1234/p2p/16Uiu2HAmPxGNWu9eVAQPJww79J32pTJLKGcpjRMb4Qb8xxKkyuG1","/ip4/52.52.127.117/udp/1234/p2p/16Uiu2HAm93Hd5azfhkGBbkx1zero3nYHvfjQYM2NtiW4R3r5bE2g"]
network_libp2p_nodes = []
network_private = false
network_disable_discovery = false

db_dir = "db"

rpc_enabled = true
rpc_listen_address = "0.0.0.0:5678"
# rpc_listen_address_admin = "127.0.0.1:5679"

log_config_file = "log_config"

blockchain_rpc_endpoint = "https://rpc-testnet.0g.ai"

log_contract_address = "0x22C1CaF8cbb671F220789184fda68BfD7eaA2eE1"
mine_contract_address = "0x8B9221eE2287aFBb34A7a1Ef72eB00fdD853FFC2"

log_sync_start_block_number = 512567
log_page_size = 999

# [sync]
# auto_sync_enabled = false
# max_sync_files = 8
# find_peer_timeout = "30s"
# sync_file_by_rpc_enabled = true
# sync_file_on_announcement_enabled = false

# [miner]
# miner_id
# miner_key
